package com.monikamorrow.burp;

import burp.ITab;
import burp.IBurpExtenderCallbacks;
import java.awt.Component;
import javax.swing.JPanel;

public class UrlScopeComponent extends javax.swing.JPanel {
    IBurpExtenderCallbacks mCallbacks;
    
    /**
     * Creates new form BurpSuiteTab
     * @param customPanel The panel to be added to the GUI
     * @param tabName     The name displayed on the tab
     * @param callbacks   For UI Look and Feel
     */
    public UrlScopeComponent(IBurpExtenderCallbacks callbacks) {
        mCallbacks = callbacks;
        
	initComponents();
        mCallbacks.customizeUiComponent(jRadioButtonInScopeRequests);
        mCallbacks.customizeUiComponent(jRadioButtonAllRequests);
        
        buttonGroupDefineScope.add(jRadioButtonInScopeRequests);
        buttonGroupDefineScope.add(jRadioButtonAllRequests);
        
        restoreSavedSettings();
    }
    
    public void addComponent(JPanel customPanel) {
        JPanel newPanel = (JPanel)this.add(customPanel);
        this.doLayout();
        newPanel.setLocation(275,0);
    }
    
    /**
     * Returns true if all response times should be calculated
     * @return true if the GUI indicates all requests should be processed
     */
    public boolean processAllRequests() {
        return jRadioButtonAllRequests.isSelected();
    }

    /**
     * Save all configured settings
     */
    public void saveSettings() {
        // Clear settings
        mCallbacks.saveExtensionSetting("O_SCOPE", null);

        // Set any selected checkboxes in settings
        if(jRadioButtonAllRequests.isSelected()) {
            mCallbacks.saveExtensionSetting("O_SCOPE", "ALL");
        }
    }
    
    /**
     * Restores any found saved settings
     */
    public void restoreSavedSettings() {
        boolean scopeAllSel = false;
        
        if(mCallbacks.loadExtensionSetting("O_SCOPE") != null ) {
            scopeAllSel = getSetting("O_SCOPE");
        }
        jRadioButtonAllRequests.setSelected(scopeAllSel);
    }
    
    /**
     * Get the boolean value of the requested setting
     * @param name
     * @return whether the setting was selected
     */
    private boolean getSetting(String name) {
        if(name.equals("O_SCOPE") && mCallbacks.loadExtensionSetting(name).equals("ALL") == true) {
            return true;
        }
        else return mCallbacks.loadExtensionSetting(name).equals("ENABLED") == true;
    }


 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDefineScope = new javax.swing.ButtonGroup();
        buttonGroupChars = new javax.swing.ButtonGroup();
        jRadioButtonInScopeRequests = new javax.swing.JRadioButton();
        jRadioButtonAllRequests = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonSaveSettings = new javax.swing.JButton();

        jRadioButtonInScopeRequests.setSelected(true);
        jRadioButtonInScopeRequests.setText("In scope requests");

        jRadioButtonAllRequests.setText("All requests");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(229, 137, 0));
        jLabel3.setText("URL Scope");

        jLabel5.setText("Select the configuration this extention will act on:");

        jButtonSaveSettings.setText("Save Settings");
        jButtonSaveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addComponent(jRadioButtonInScopeRequests)
                        .addComponent(jRadioButtonAllRequests))
                    .addComponent(jButtonSaveSettings))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonInScopeRequests)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonAllRequests)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSaveSettings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.getAccessibleContext().setAccessibleName("Select the configuration this extenstion applies to:");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveSettingsActionPerformed
        saveSettings();
    }//GEN-LAST:event_jButtonSaveSettingsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupChars;
    private javax.swing.ButtonGroup buttonGroupDefineScope;
    private javax.swing.JButton jButtonSaveSettings;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonAllRequests;
    private javax.swing.JRadioButton jRadioButtonInScopeRequests;
    // End of variables declaration//GEN-END:variables

}
